### ISSUE TITLE
Upmem SDK 2019.4.0

### ISSUE THREAD

**Issue by jehuty0shift** [upmem/lucene-solr#2]
Hello, I would like to experiment with the latest code of UPMEM Lucene-solr. But it needs the new upmem SDK 2019.4.0. Do you have any plan to publish it ? 

this commit change the dependency of the SDK. 
https://github.com/upmem/lucene-solr/commit/516590c0f7be51ef5d7694e43eb00b4e325a05a3

**Comment by vpalatin** [comment]
Hey,

2019.4.0 is not completed yet, we should publish it sometime in January.
Contrary to a few other applications, sadly this one has no branch per SDK version but removing the last few commits might work well, I don't see anything critical in the ones dependent on the new SDK.

**Comment by jehuty0shift** [comment]
Thanks for the reply, i did what you suggested before opening the issue. It works of course. Another quick question, do you plan to port your lucene-solr version to more recent versions like 8.3 or even master ? The goal here would be to build an Elasticsearch upmem compatible version.
